
struct Sentinel1RawPacket {
    uint8_t PacketVersionNumber;
    uint8_t PacketType;
    uint32_t Time;
    uint16_t FineTime;
    uint32_t SyncMarker;
    uint32_t DataTakeID;
    uint8_t ECCNumber;
    uint8_t TestMode;
    bool RxChannelId;
    uint32_t InstrumentConfigID;
    uint8_t WordIndex;
    uint16_t WordVal;
    uint32_t SpacePacketCount;
    uint32_t PRICount;
    uint8_t BAQMode;
    bool ErrorFlag;
    uint8_t BAQBlockLength;
    uint8_t RangeDecimation;
    uint8_t RxGain;
    uint16_t TxRampRate;
    uint16_t TxPulseStartFreq;
    uint32_t TxPulseLength;
    uint8_t Rank;
    uint32_t PulseRepetitionInterval;
    uint32_t SamplingWindowStartTime;
    uint32_t SamplingWindowLength;
    uint8_t Polarisation;
    uint8_t TemperatureCompensation;
    uint8_t ElevationBeamAddress;
    uint16_t AzimuthBeamAddress;
    bool SASTestMode;
    uint8_t CalType;
    uint16_t CalibrationBeamAddress;
};